name: vm-NAP
channels:
  - conda-forge
  - 3d-e-Chem
  - bioconda
  - rdkit
dependencies:
  - numpy
  - pandas
  #- rdkit
  - sygma
  #- java-jdk  
  - rdkit::rdkit
  - molvs
  - jupyter
  - ipykernel
  - pip
    - streamlit

  