name: vm-NAP
channels:
  - conda-forge
  - 3d-e-Chem
  - bioconda
dependencies:
  - python=3.10  # or another version as per your requirement
  - numpy
  - pandas
  - sygma
  - rdkit
  - molvs
  - jupyter
  - ipykernel
  - openjdk
  - pip
  - pip:
      - streamlit
  # Uncomment the next line if Java is needed
  # - openjdk
  # - java-jdk