name: vm-NAP
channels:
  - conda-forge
  - 3d-e-Chem
  - bioconda
dependencies:
  - python=3.9
  - numpy
  - pandas
  - jupyter
  - ipykernel
  - openjdk
  - pip
  - ipython
  - unzip
  - requests
  - pip:
      - streamlit
