name: vm-NAP
channels:
  - conda-forge
  - 3d-e-Chem
  - bioconda
dependencies:
  - python=3.9
  - numpy
  - pandas
  - sygma
  - rdkit
  - molvs
  - jupyter
  - ipykernel
  - openjdk
  - pip
  - ipython
  - unzip
  - pip:
      - streamlit
