name: vm-NAP
channels:
  - conda-forge
  - 3d-e-Chem
  - bioconda
dependencies:
  - python=3.9
  - numpy
  - pandas
  - jupyter
  - ipykernel
  - openjdk
  - pip
  - ipython
  - requests
  - rdkit
  - pip:
      - streamlit
      - git+https://github.com/lfnothias/gnps_postprocessing.git@lfnothias-patch-1#egg=gnps_postprocessing
      - git+https://github.com/3D-e-Chem/sygma@master#egg=sygma