name: vm-NAP
channels:
  - conda-forge
  - 3d-e-Chem
  - bioconda
  - rdkit
dependencies:
  - numpy
  - pandas
  - sygma
  - rdkit::rdkit
  - molvs
  - jupyter
  - ipykernel
  - pip
  - streamlit
  - java-jdk  

  
